### ISSUE TITLE
TypeError (rails 7.0.0.rc1)

### ISSUE THREAD

**Issue by tkeo** [asakusarb/action_args#32]
`rails s` raises TypeError in rails 7.0.0.rc1 project.

versions:
- ruby 3.0.3
- rails 7.0.0.rc1
- action_args 2.6.0

backtrace:
```
/srv/vendor/bundle/ruby/3.0.0/gems/action_args-2.6.0/lib/action_args/callbacks.rb:63:in `<module:Callbacks>': CallTemplate is not a class (TypeError)
/srv/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.0.rc1/lib/active_support/callbacks.rb:375: previous definition of CallTemplate was here
 from /srv/vendor/bundle/ruby/3.0.0/gems/action_args-2.6.0/lib/action_args/callbacks.rb:62:in `<module:ActiveSupport>'
 from /srv/vendor/bundle/ruby/3.0.0/gems/action_args-2.6.0/lib/action_args/callbacks.rb:61:in `<main>'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/action_args-2.6.0/lib/action_args.rb:5:in `<main>'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
 from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
 from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:55:in `each'
 from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
 from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:44:in `each'
 from /usr/local/lib/ruby/3.0.0/bundler/runtime.rb:44:in `require'
 from /usr/local/lib/ruby/3.0.0/bundler.rb:175:in `require'
 from /srv/config/application.rb:19:in `<main>'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/railties-7.0.0.rc1/lib/rails/commands/server/server_command.rb:137:in `block in perform'
 from <internal:kernel>:90:in `tap'
 from /srv/vendor/bundle/ruby/3.0.0/gems/railties-7.0.0.rc1/lib/rails/commands/server/server_command.rb:134:in `perform'
 from /srv/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
 from /srv/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
 from /srv/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
 from /srv/vendor/bundle/ruby/3.0.0/gems/railties-7.0.0.rc1/lib/rails/command/base.rb:87:in `perform'
 from /srv/vendor/bundle/ruby/3.0.0/gems/railties-7.0.0.rc1/lib/rails/command.rb:48:in `invoke'
 from /srv/vendor/bundle/ruby/3.0.0/gems/railties-7.0.0.rc1/lib/rails/commands.rb:18:in `<main>'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
 from /srv/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
 from bin/rails:4:in `<main>'
```

**Comment by tkeo** [comment]
v2.7.0 works well!
Thanks!
